import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    appName: "TransOps Control",
    appTagline: "Operations Control Dashboard",
    dashboard: "Dashboard",
    shipments: "Shipments",
    customers: "CRM",
    transporters: "Transporters",
    plantAnalytics: "Plants",
    performance: "Performance",
    totalShipments: "Total Shipments",
    activeShipments: "Active Shipments",
    onTimeRate: "On-Time Rate",
    totalRevenue: "Total Revenue",
    avgTransitDays: "Avg Transit Days",
    totalCustomers: "Total Customers",
    ptl: "PTL",
    ftl: "FTL",
    ptlShipments: "PTL Shipments",
    ftlShipments: "FTL Shipments",
    shipmentType: "Shipment Type",
    all: "All",
    allPlants: "All Plants",
    allDivisions: "All Divisions",
    allTransporters: "All Transporters",
    allStatuses: "All Statuses",
    plant: "Plant",
    division: "Division",
    transporter: "Transporter",
    status: "Status",
    scheduled: "Scheduled",
    in_transit: "In Transit",
    delivered: "Delivered",
    delayed: "Delayed",
    cancelled: "Cancelled",
    active: "Active",
    inactive: "Inactive",
    prospect: "Prospect",
    churned: "Churned",
    enterprise: "Enterprise",
    mid_market: "Mid-Market",
    small_business: "Small Business",
    startup: "Startup",
    loading: "Loading...",
    noData: "No data available.",
    shipmentsByType: "Shipments by Type",
    shipmentsByStatus: "Shipments by Status",
    monthlyVolume: "Monthly Volume",
    transporterPerformance: "Transporter Performance",
    onTimeVsDelayed: "On-Time vs Delayed",
    costPerKm: "Cost per KM",
    plantPerformance: "Plant Performance",
    divisionOverview: "Division Overview",
    customerSegments: "Customer Segments",
    topCustomers: "Top Customers",
    revenueByDivision: "Revenue by Division",
    utilizationRate: "Utilization Rate",
    dispatchRate: "Dispatch Rate",
    fleetSize: "Fleet Size",
    rating: "Rating",
    damageRate: "Damage Rate",
    satisfaction: "Satisfaction",
    revenue: "Revenue",
    shipmentCount: "Shipments",
    weight: "Weight (kg)",
    distance: "Distance (km)",
    cost: "Cost",
    date: "Date",
    customer: "Customer",
    origin: "Origin",
    destination: "Destination",
    filters: "Filters",
    clearFilters: "Clear Filters",
    ptlFtlBreakdown: "PTL/FTL Breakdown",
    performanceByPlant: "Performance by Plant",
    performanceByTransporter: "Performance by Transporter",
    performanceByDivision: "Performance by Division",
    operational: "Operational",
    maintenance: "Maintenance",
    closed: "Closed",
    suspended: "Suspended",
    segment: "Segment",
    location: "Location",
    contact: "Contact",
    lastShipment: "Last Shipment",
    target: "Target",
    actual: "Actual",
  },
  es: {
    appName: "TransOps Control",
    appTagline: "Tablero de Control de Operaciones",
    dashboard: "Panel",
    shipments: "Envíos",
    customers: "CRM",
    transporters: "Transportistas",
    plantAnalytics: "Plantas",
    performance: "Rendimiento",
    totalShipments: "Envíos Totales",
    activeShipments: "Envíos Activos",
    onTimeRate: "Tasa a Tiempo",
    totalRevenue: "Ingresos Totales",
    avgTransitDays: "Días Promedio Tránsito",
    totalCustomers: "Clientes Totales",
    ptl: "PTL",
    ftl: "FTL",
    ptlShipments: "Envíos PTL",
    ftlShipments: "Envíos FTL",
    shipmentType: "Tipo de Envío",
    all: "Todos",
    allPlants: "Todas las Plantas",
    allDivisions: "Todas las Divisiones",
    allTransporters: "Todos los Transportistas",
    allStatuses: "Todos los Estados",
    plant: "Planta",
    division: "División",
    transporter: "Transportista",
    status: "Estado",
    scheduled: "Programado",
    in_transit: "En Tránsito",
    delivered: "Entregado",
    delayed: "Retrasado",
    cancelled: "Cancelado",
    active: "Activo",
    inactive: "Inactivo",
    prospect: "Prospecto",
    churned: "Perdido",
    enterprise: "Empresa",
    mid_market: "Mediana Empresa",
    small_business: "Pequeña Empresa",
    startup: "Startup",
    loading: "Cargando...",
    noData: "No hay datos disponibles.",
    shipmentsByType: "Envíos por Tipo",
    shipmentsByStatus: "Envíos por Estado",
    monthlyVolume: "Volumen Mensual",
    transporterPerformance: "Rendimiento de Transportistas",
    onTimeVsDelayed: "A Tiempo vs Retrasado",
    costPerKm: "Costo por KM",
    plantPerformance: "Rendimiento por Planta",
    divisionOverview: "Resumen por División",
    customerSegments: "Segmentos de Clientes",
    topCustomers: "Principales Clientes",
    revenueByDivision: "Ingresos por División",
    utilizationRate: "Tasa de Utilización",
    dispatchRate: "Tasa de Despacho",
    fleetSize: "Tamaño de Flota",
    rating: "Calificación",
    damageRate: "Tasa de Daño",
    satisfaction: "Satisfacción",
    revenue: "Ingresos",
    shipmentCount: "Envíos",
    weight: "Peso (kg)",
    distance: "Distancia (km)",
    cost: "Costo",
    date: "Fecha",
    customer: "Cliente",
    origin: "Origen",
    destination: "Destino",
    filters: "Filtros",
    clearFilters: "Limpiar Filtros",
    ptlFtlBreakdown: "Desglose PTL/FTL",
    performanceByPlant: "Rendimiento por Planta",
    performanceByTransporter: "Rendimiento por Transportista",
    performanceByDivision: "Rendimiento por División",
    operational: "Operacional",
    maintenance: "Mantenimiento",
    closed: "Cerrado",
    suspended: "Suspendido",
    segment: "Segmento",
    location: "Ubicación",
    contact: "Contacto",
    lastShipment: "Último Envío",
    target: "Meta",
    actual: "Real",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");
  const toggleLanguage = () => setLanguage((l) => (l === "en" ? "es" : "en"));
  const t = (key) => translations[language]?.[key] || key;
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
